#! /bin/sh

set -x

##### Définition des variables

IF_PROD="eno1";
IF_EXT="enp0s20u2";
IF_WLAN="wlp2s0";
NULL_IP="0.0.0.0";

##### Fonctions

function open_out_tcp_strict () {
    iptables -t filter -A OUTPUT -o $1 -s $2 -d $3   \
        -p tcp --dport $4 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT;

    iptables -t filter -A INPUT  -i $1 -s $3 -d $2 \
        -p tcp --sport $4 -m conntrack --ctstate     RELATED,ESTABLISHED -j ACCEPT;
}

function open_in_tcp_strict () {
    iptables -t filter -A INPUT -i $1 -s $2 -d $3   \
        -p tcp --dport $4 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT;

    iptables -t filter -A OUTPUT  -o $1 -s $3 -d $2 \
        -p tcp --sport $4 -m conntrack --ctstate     RELATED,ESTABLISHED -j ACCEPT;
}

function open_out_udp_strict () {
    iptables -t filter -A OUTPUT -o $1 -s $2 -d $3   \
        -p udp --dport $4 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT;

    iptables -t filter -A INPUT  -i $1 -s $3 -d $2 \
        -p udp --sport $4 -m conntrack --ctstate     RELATED,ESTABLISHED -j ACCEPT;
}

function open_out_tcp_any () {
    iptables -t filter -A OUTPUT -o $1 -s $2   \
        -p tcp --dport $3 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT;

    iptables -t filter -A INPUT  -i $1   -d $2 \
        -p tcp --sport $3 -m conntrack --ctstate     RELATED,ESTABLISHED -j ACCEPT;
}

function get_ip () {
    if [ -d /sys/class/net/"$1" ]; then
        _ret=`ip -4 -o addr show "$1" | sed 's+.*inet \(.*\)/.*+\1+'`;
        [[ "${_ret}" == "" ]] && _ret=$NULL_IP;
        echo ${_ret};
    else
        echo $NULL_IP;
    fi
}

function get_dns () {
    tac /etc/resolv.conf | grep nameserver | awk '{print $2}';
}

function resolv () {
    (nslookup "$1" | grep -A1 "Name:" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | tr '\n' ',') 2> /dev/null;
}

MY_IP_EXT=`get_ip $IF_EXT`;
MY_IP_PROD=`get_ip $IF_PROD`;
MY_IP_WLAN=`get_ip $IF_WLAN`;

if ( ip link show "$1" > /dev/null 2>&1 ); then # si inet en argument
    MY_IP_PROD=`get_ip "$1"` && IF_PROD="$1";

elif [[ "$MY_IP_EXT" != "$NULL_IP" ]]; then     # sinon si utilisation connexion téléphone
    MY_IP_PROD=$MY_IP_EXT && IF_PROD=$IF_EXT;

elif [[ "$MY_IP_WLAN" != "$NULL_IP" ]]; then    # sinon si utilisation connexion WiFi
    MY_IP_PROD=$MY_IP_WLAN && IF_PROD=$IF_WLAN;
fi

##### Nettoyage des règles existantes
iptables -F; # Flush (supression des règles)
iptables -X; # Supression des chaînes perso

##### Règles de filtrages

# Par défaut, tout est interdit : bonne pratique de sécurité
# On bloque tout silencieusement…

iptables -t filter -P INPUT DROP;
iptables -t filter -P FORWARD DROP;
iptables -t filter -P OUTPUT DROP;

# Journaliser tout ce qu'on rejette
iptables -N LOG_DROP;
iptables -A LOG_DROP -j LOG --log-prefix '[IPTABLES DROP]: ';
iptables -A LOG_DROP -j DROP;

# Éventuellement : journaliser protection contre le scan de port
iptables -N LOG_TARPIT;
iptables -A LOG_TARPIT -p tcp -j LOG --log-prefix '[IPTABLES TARPIT]: ';
iptables -A LOG_TARPIT -p tcp -j TARPIT;
iptbales -A LOG_TARPIT -j LOG_DROP;

# Journaliser certaines choses qu'on accepte
iptables -N LOG_ACCEPT;
iptables -A LOG_ACCEPT -j LOG --log-prefix '[IPTABLES ACCEPT]: ';
iptables -A LOG_ACCEPT -j ACCEPT;

for dns in `get_dns`; do
    iptables -t filter -A OUTPUT -o $IF_PROD -s $MY_IP_PROD -d $dns \
        -p udp -m udp --dport 53 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT;

    iptables -t filter -A INPUT  -i $IF_PROD -d $MY_IP_PROD -s $dns \
        -p udp -m udp --sport 53 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT;
done;

# Ports sortant ICMP
iptables -t filter -A OUTPUT -o $IF_PROD -s $MY_IP_PROD \
    -p icmp --icmp-type echo-request -j LOG_ACCEPT;

iptables -t filter -A INPUT  -i $IF_PROD -d $MY_IP_PROD \
    -p icmp --icmp-type echo-reply -j LOG_ACCEPT;

# Ports habituels sur le web
for tcp_port in 443 80; do
    open_out_tcp_any $IF_PROD $MY_IP_PROD $tcp_port;
done;

# Local ports
open_out_tcp_strict lo 127.0.0.1 127.0.0.1 39725    #GoogleTalk
open_out_tcp_strict lo 127.0.0.1 127.0.0.1 53927    #GoogleTalk
open_in_tcp_strict  lo 127.0.0.1 127.0.0.1 39725    #GoogleTalk
open_in_tcp_strict  lo 127.0.0.1 127.0.0.1 53927    #GoogleTalk
open_out_tcp_strict lo 127.0.0.1 127.0.0.1 631      #CUPS

# Open myfirm special ports if needed
if [[ "$( (nslookup $dns | grep name | awk '{print $4}') 2> /dev/null)" == "ns2.myfirm.eu." ]]; then
    _smtp=$(resolv smtp.myfirm.eu);
    _imap=$(resolv imap.myfirm.eu);
    _xmpp=$(resolv xmpp.myfirm.eu);
    open_out_tcp_strict $IF_PROD $MY_IP_PROD ${_smtp:0:-1} 25;   # smtp interne
    open_out_tcp_strict $IF_PROD $MY_IP_PROD ${_imap:0:-1} 143;  # imap
    open_out_tcp_strict $IF_PROD $MY_IP_PROD ${_xmpp:0:-1} 5222; # imap

    _f1=$(resolv filer1.myfirm.eu);
    _f2=$(resolv filer2.myfirm.eu);
    open_out_tcp_strict $IF_PROD $MY_IP_PROD ${_f1}${_f2:0:-1} 445; # tcp smb
    open_out_udp_strict $IF_PROD $MY_IP_PROD ${_f1}${_f2:0:-1} 445; # udp smb

    ### printers ###
    _printers="192.168.123.123,192.168.234.234";

    #### Contact printer → mDNS (if avahi-daemon.socket)
    iptables -t filter -A OUTPUT -o $IF_PROD -s $MY_IP_PROD -d 224.0.0.251 \
        -p udp --dport 5353 --sport 5353 -j ACCEPT;
    iptables -t filter -A INPUT  -i $IF_PROD -s $_printers -d 224.0.0.251 \
        -p udp --dport 5353 --sport 5353 -j ACCEPT;

    #### File Transfert
    open_out_tcp_strict $IF_PROD $MY_IP_PROD $_printers 9100;

fi

# Open external usage
open_out_tcp_strict $IF_PROD $MY_IP_PROD 192.30.252.0/22 ssh; #github

_off365=$(resolv outlook.office365.com); ##### Office365 IMAP, SMTP
open_out_tcp_strict $IF_PROD $MY_IP_PROD ${_off365:0:-1} 587;
open_out_tcp_strict $IF_PROD $MY_IP_PROD ${_off365:0:-1} 143;

# Don't log broadcast, mDNS
iptables -t filter -A INPUT -m pkttype --pkt-type broadcast -j DROP;
iptables -t filter -A INPUT -d 224.0.0.251 -p udp --dport 5353 --sport 5353 -j DROP;

# LogNdrop
iptables -t filter -A INPUT -i $IF_PROD -j LOG_TARPIT;
iptables -t filter -A INPUT  -j LOG_DROP;
iptables -t filter -A OUTPUT -j LOG_DROP;
