#!/bin/sh
#
# fluxbox startup-script:
#

# Lines starting with a '#' are ignored.

function delay {
    sleep $2;
    eval "$1" &
}

function rdombg {
    while true; do
        feh --randomize --bg-fill ~/.wallpaper/*;
        sleep 60;
    done;
}

function vbox {
    for feature in --clipboard --draganddrop --seamless --display --checkhostversion;
    do
        VBoxClient ${feature}
    done;
}

# Change your keymap:
xmodmap "~/.Xmodmap"
setxkbmap fr oss;
xrdb -merge ~/.Xresources

## composite
#delay "xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55" 5 &
#delay "compton -c -r4 -l-6 -t-4 -z -b -G -C -e0.85 -f -D30 -I0.45 -O0.45 --paint-on-overlay --unredir-if-possible --backend glx --glx-no-stencil --glx-no-rebind-pixmap" 5 &

## témoin de charge
#delay "cbatticon" 6 &

#delay rdombg 6 &

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/trouat/.fluxbox/log"
